### PR TITLE
viewWillAppear and viewDidAppear

### PR DESCRIPTION
**Pull request by leonardoobaptistaa**
added support to natives viewWillAppear and viewDidAppear for UIViewControllers

### CODE REVIEW

**Comment by jinthagerman** [comment]
Please note viewwillappear and viewdidappear will be called twice on ios 5.

**Comment by leonardoobaptistaa** [comment]
Are you sure? I tested here, Simulator iOS 5, iphone iOS 5.1 and its called just once.

My test is push a viewcontroller into a navigationcontroller with [self.navigationController pushViewController: controller animated:YES];

**Comment by jinthagerman** [comment]
Strange, Ill test again

**Comment by dave-trudes** [comment]
Please send messages (viewWillDisappear & viewDidDisappear) to displayed view controller before switching it.
thx

**Comment by jinthagerman** [comment]
I'll add them in my next commit. Thanks

**Comment by jinthagerman** [comment]
Leonardo - when you switch between tabs on iOS 5, it will call viewWillAppear and viewDidAppear. Will implement a workaround

**Comment by leonardoobaptistaa** [comment]
hey Jin,

but this is normal behavior, will appear before view shows up and did appear when it is on the screen.

Leonardo Baptista

Em 08/04/2012, às 07:32, Jin Budelmannreply@reply.github.com escreveu:

**Comment by jinthagerman** [comment]
Yup, I mean they are called twice on iOS 5 when you switch tabs. This shouldn't be an issue now however.

**Comment by leonardoobaptistaa** [comment]
nice :)

2012/4/9 Jin Budelmann <
reply@reply.github.com

**Pull request merged**
